version: "3.8"

services:     
 web:
#   image: psbernardo/test-grpc-docker-gitactions_web
  build: .
  container_name: "grpc-go"
  ports:
   - "9010:9010"
   - "9011:9011"
  command: /main db migrate
  command: /main server start
  environment: 
   TESTDB: "sqlserver://patrick:trustno1@192.168.254.124:1434?database=testdb"
  volumes: 
   - C:/Users/pat/dockerfiles:/data01
  extra_hosts: 
   - "loghost:192.168.254.124"
  networks:
   - dockernet

services:     
 web:
#   image: psbernardo/test-grpc-docker-gitactions_web
  build: .
  container_name: "goclearing-migration"
  ports:
   - "9010:9010"
   - "9011:9011"
  command: /main db migrate
  environment: 
   TESTDB: "sqlserver://patrick:trustno1@192.168.254.124:1434?database=testdb"
  extra_hosts: 
   - "loghost:192.168.254.124"
  networks:
   - dockernet
   
 
networks:
 dockernet:
  external: true
   
  